# Generated by Django 4.0.2 on 2022-05-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=500)),
                ('rent', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
